import copy
import io
import json
import math
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

import numpy as np
import torch

from src.benchmarking.config import read_json
from src.policies.config import ModelConfig
from src.policies.features import (
    BIOMES, ENTITY_DIM, ENTITY_TYPES, FEATURE_VERSION, PEER_ENERGY_UNAVAILABLE,
    PEER_FEATURE_VERSION, PUBLIC_FEATURE_VERSION, FeatureBatch, encode_step, feature_version,
)
from src.policies.networks import PolicyNetwork
from src.policies.neural import NeuralPolicy
from src.training.artifacts import file_hash, load_checkpoint, save_checkpoint, write_json
from src.training.imitation import ImitationDataset
from src.training.offline_bc import (
    cache_frames, forward_sequence, migrate_peer_context, pack_sequence, reset_peer_context_optimizer,
)
from src.training.rollout import Rollout, RolloutCollector, align_hidden
from tests.test_pipeline_contract import pipeline_config
from tests.test_policy_features import agent, frame
from tests.test_training_rollout import ConstantTeacher, ScriptedEnvironment, TinyPolicy, make_config, make_frame


def peer_step():
    return frame([
        agent(2, [
            {"type": "Fruit", "distance": 10, "angle": 0},
            {"type": "Tree", "distance": 20, "angle": math.pi / 2},
            {"type": "Predator", "distance": 30, "angle": -0.25, "rel_dir": 0.4},
            {"type": "Agent", "id": 9, "distance": 40, "angle": 0.2, "rel_dir": -0.3},
            {"type": "Agent", "id": 31, "distance": 80, "angle": -0.4, "rel_dir": 0.7},
            {"type": "Agent", "id": 99, "distance": 120, "angle": 0.5, "rel_dir": 0},
            {"type": "Edge", "coords": [[50, -10], [50, 10]]},
        ]),
        agent(9, [{"type": "Agent", "id": 2, "distance": 40, "angle": -0.2, "rel_dir": 0.3}],
              energy=240, max_energy=400),
        agent(31, energy=45, max_energy=300),
    ])


def peer_model(**changes):
    return ModelConfig(hidden_size=16, entity_size=8, public_context=True, peer_context=True, **changes)


class PeerContextTests(unittest.TestCase):
    def setUp(self):
        torch.set_num_threads(1)
        self.enterContext(torch.random.fork_rng(devices=[]))
        torch.manual_seed(341)
        self.enterContext(patch("src.core.SimulationCore.__init__", side_effect=AssertionError("No simulator")))

    def assert_batch_equal(self, left, right):
        self.assertEqual(left.agent_ids, right.agent_ids)
        self.assertEqual(left.feature_version, right.feature_version)
        for name in ("scalars", "entities", "entity_types", "entity_owners"):
            np.testing.assert_array_equal(getattr(left, name), getattr(right, name))

    def test_opt_in_requires_public_context(self):
        self.assertFalse(ModelConfig().peer_context)
        with self.assertRaisesRegex(ValueError, "public_context"):
            ModelConfig(peer_context=True)
        with self.assertRaisesRegex(ValueError, "public_context"):
            encode_step(peer_step(), peer_context=True, validate=False)
        self.assertEqual(feature_version(False), FEATURE_VERSION)
        self.assertEqual(feature_version(True), PUBLIC_FEATURE_VERSION)
        self.assertEqual(feature_version(True, True), PEER_FEATURE_VERSION)

    def test_legacy_inputs_and_prechange_deterministic_actions_are_unchanged(self):
        step = peer_step()
        # Captured from the dirty pre-peer implementation, not regenerated by this test.
        expected = {
            False: [
                [9.476922750473022, 0.01862312708799469, 0.1054792725379422, False],
                [9.478644728660583, 0.020108879855561132, 0.10629251454987913, False],
                [4.739163815975189, 0.019725915697852495, 0.10613006042301268, False],
            ],
            True: [
                [10.795401334762573, 0.6181343363933867, 0.2583963906754218, True],
                [10.794581174850464, 0.6206956367732568, 0.2578774409676549, True],
                [5.39711058139801, 0.6216687932862746, 0.2583881281141101, False],
            ],
        }
        for public in (False, True):
            with self.subTest(public=public):
                features = encode_step(step, public_context=public)
                self.assert_batch_equal(features, encode_step(step, public_context=public, peer_context=False))
                np.testing.assert_array_equal(features.entities[:, 8:], 0)
                np.testing.assert_allclose(features.scalars[0], [
                    0.3, 0.3, 1 / 120, 0.5, 0.5, 0.5, 0.5, 1 / 3, 0.5, 1 / 3000,
                    math.log1p(3) / 5, *(float(biome == "forest") for biome in BIOMES),
                    *([math.log1p(2), 1 / 3000, 0] if public else []), 0, 0, 1, 0, 1, 0,
                ], rtol=1e-6)
                torch.manual_seed(341)
                network = PolicyNetwork(ModelConfig(hidden_size=16, entity_size=8, public_context=public))
                actions = NeuralPolicy(network, 1).act(step)
                self.assertEqual([action.agent_id for action in actions], [2, 9, 31])
                np.testing.assert_allclose([
                    [a.move_distance, a.move_direction, a.turn_angle] for a in actions
                ], np.asarray(expected[public])[:, :3], atol=2e-6, rtol=1e-6)
                self.assertEqual([a.spawn_agent for a in actions], [row[3] for row in expected[public]])

    def test_public_energy_is_joined_by_observed_id_and_only_agent_tail_changes(self):
        step = peer_step()
        old = encode_step(step, public_context=True)
        new = encode_step(step, public_context=True, peer_context=True)
        self.assertEqual(new.entities.shape, (8, ENTITY_DIM))
        self.assertEqual(new.agent_ids, (2, 9, 31))
        self.assertEqual(new.feature_version, PEER_FEATURE_VERSION)
        for name in ("scalars", "entity_types", "entity_owners"):
            np.testing.assert_array_equal(getattr(old, name), getattr(new, name))
        np.testing.assert_array_equal(old.entities[:, :8], new.entities[:, :8])
        agents = new.entity_types == ENTITY_TYPES.index("Agent")
        np.testing.assert_array_equal(old.entities[~agents], new.entities[~agents])
        np.testing.assert_allclose(new.entities[agents, 8:], [
            [0.6, math.log1p(9)], [0.15, math.log1p(31)],
            [PEER_ENERGY_UNAVAILABLE, math.log1p(99)], [0.3, math.log1p(2)],
        ], rtol=1e-6)

    def test_untagged_legacy_batches_remain_usable_but_never_imply_peer_semantics(self):
        for public in (False, True):
            encoded = encode_step(peer_step(), public_context=public)
            untagged = FeatureBatch(encoded.agent_ids, encoded.scalars, encoded.entities,
                                    encoded.entity_types, encoded.entity_owners)
            self.assert_batch_equal(encoded, untagged)
            network = PolicyNetwork(ModelConfig(hidden_size=16, entity_size=8, public_context=public))
            with torch.no_grad():
                torch.testing.assert_close(network(encoded).mean, network(untagged).mean, atol=0, rtol=0)
        encoded = encode_step(peer_step(), public_context=True, peer_context=True)
        untagged = FeatureBatch(encoded.agent_ids, encoded.scalars, encoded.entities,
                                encoded.entity_types, encoded.entity_owners)
        with self.assertRaisesRegex(ValueError, "schema"):
            PolicyNetwork(peer_model())(untagged)

    def test_public_peer_join_has_no_population_or_observation_cap(self):
        count = 137
        step = frame([
            agent(index, [{"type": "Agent", "id": (index + 1) % count, "distance": index + 1,
                           "angle": 0, "rel_dir": 0}], energy=index + 1, max_energy=200)
            for index in reversed(range(count))
        ])
        encoded = encode_step(step, public_context=True, peer_context=True)
        self.assertEqual(encoded.agent_ids, tuple(reversed(range(count))))
        self.assertEqual(encoded.entities.shape, (count, ENTITY_DIM))
        np.testing.assert_array_equal(encoded.entity_owners, np.arange(count))
        peers = [(index + 1) % count for index in reversed(range(count))]
        np.testing.assert_allclose(encoded.entities[:, 8], [(index + 1) / 200 for index in peers], rtol=1e-6)
        np.testing.assert_allclose(encoded.entities[:, 9], np.log1p(peers), rtol=1e-6)

    def test_observed_id_swap_is_distinguishable_even_when_peer_energy_matches(self):
        step = peer_step()
        step.agent_status[2].energy = 180
        swapped = step.model_copy(deep=True)
        for observation in swapped.agent_status[0].observations:
            if observation.get("id") in (9, 31):
                observation["id"] = 31 if observation["id"] == 9 else 9
        self.assert_batch_equal(encode_step(step, public_context=True), encode_step(swapped, public_context=True))
        left = encode_step(step, public_context=True, peer_context=True)
        right = encode_step(swapped, public_context=True, peer_context=True)
        for name in ("scalars", "entity_types", "entity_owners"):
            np.testing.assert_array_equal(getattr(left, name), getattr(right, name))
        np.testing.assert_array_equal(left.entities[:, :9], right.entities[:, :9])
        self.assertFalse(np.array_equal(left.entities[:, 9], right.entities[:, 9]))
        network = PolicyNetwork(peer_model())
        with torch.no_grad():
            self.assertFalse(torch.equal(network(left).mean, network(right).mean))

    def test_missing_stale_and_dead_status_keeps_identity_without_healthy_defaults(self):
        for energy in (0, -4):
            step = peer_step()
            step.agent_status[2].energy = energy
            step.agent_status.pop(1)
            step.n_agents = len(step.agent_status)
            features = encode_step(step, public_context=True, peer_context=True)
            rows = features.entities[features.entity_types == ENTITY_TYPES.index("Agent")]
            np.testing.assert_array_equal(rows[:, 8], PEER_ENERGY_UNAVAILABLE)
            np.testing.assert_allclose(rows[:, 9], np.log1p([9, 31, 99]), rtol=1e-6)
        fresh = encode_step(peer_step(), public_context=True, peer_context=True)
        self.assertAlmostEqual(float(fresh.entities[3, 8]), 0.6, places=6)
        for empty in (frame([]), frame([]).model_copy(update={"n_agents": 5, "score": 0, "sim_time": 0})):
            encoded = encode_step(empty, public_context=True, peer_context=True)
            self.assertEqual(encoded.entities.shape, (0, 10))
            self.assertEqual(encoded.feature_version, PEER_FEATURE_VERSION)

    def test_agent_and_observation_permutations_preserve_identity_and_predictions(self):
        step = peer_step()
        order = np.asarray([2, 0, 1])
        permuted = step.model_copy(deep=True)
        permuted.agent_status = [permuted.agent_status[index] for index in order]
        for status in permuted.agent_status:
            status.observations.reverse()
        original = encode_step(step, public_context=True, peer_context=True)
        reordered = encode_step(permuted, public_context=True, peer_context=True)
        np.testing.assert_array_equal(original.scalars[order], reordered.scalars)
        for new_owner, old_owner in enumerate(order):
            np.testing.assert_array_equal(
                original.entities[original.entity_owners == old_owner],
                reordered.entities[reordered.entity_owners == new_owner],
            )
        hidden = torch.linspace(-0.2, 0.2, 48).reshape(3, 16)
        for encoder in ("pool", "attention"):
            for memory in ("none", "gru"):
                network = PolicyNetwork(peer_model(encoder=encoder, memory=memory))
                with self.subTest(encoder=encoder, memory=memory), torch.no_grad():
                    left, right = network(original, hidden), network(reordered, hidden[order])
                    for name in ("mean", "log_std", "spawn_logits", "next_hidden"):
                        torch.testing.assert_close(getattr(left, name)[order], getattr(right, name),
                                                   atol=1e-6, rtol=1e-5)
                    torch.testing.assert_close(left.value, right.value, atol=1e-6, rtol=1e-5)
                left = NeuralPolicy(network, 1).act(step)
                right = NeuralPolicy(network, 1).act(permuted)
                self.assertEqual({a.agent_id: a for a in left}, {a.agent_id: a for a in right})

    def test_migration_copies_all_other_weights_and_preserves_initial_predictions(self):
        step = peer_step()
        old = encode_step(step, public_context=True)
        new = encode_step(step, public_context=True, peer_context=True)
        for encoder in ("pool", "attention"):
            for memory in ("none", "gru"):
                for head in ("bounded", "vector_bc"):
                    config = ModelConfig(hidden_size=16, entity_size=8, public_context=True,
                                         encoder=encoder, memory=memory, angle_head=head)
                    network = PolicyNetwork(config).eval()
                    before = {name: value.clone() for name, value in network.state_dict().items()}
                    rng = torch.random.get_rng_state().clone()
                    migrated = migrate_peer_context(network)
                    self.assertTrue(torch.equal(rng, torch.random.get_rng_state()))
                    self.assertFalse(migrated.training)
                    expected_config = config.model_dump()
                    expected_config["peer_context"] = True
                    self.assertEqual(migrated.config.model_dump(), expected_config)
                    for name, value in migrated.state_dict().items():
                        expected = before[name].clone()
                        if name == "entity_encoders.3.0.weight":
                            expected[:, 8:10] = 0
                        self.assertTrue(torch.equal(value, expected), name)
                        self.assertTrue(torch.equal(network.state_dict()[name], before[name]), name)
                    hidden = torch.linspace(-0.2, 0.2, 48).reshape(3, 16)
                    with self.subTest(encoder=encoder, memory=memory, head=head), torch.no_grad():
                        left, right = network(old, hidden), migrated(new, hidden)
                        for name in ("mean", "log_std", "spawn_logits", "value", "next_hidden", "angle_vectors"):
                            if getattr(left, name) is not None:
                                torch.testing.assert_close(getattr(left, name), getattr(right, name),
                                                           atol=1e-7, rtol=1e-6)
                    with self.assertRaisesRegex(ValueError, "schema"):
                        migrated(old)
                    with self.assertRaisesRegex(ValueError, "schema"):
                        network(new)
        with self.assertRaisesRegex(ValueError, "public_context"):
            migrate_peer_context(PolicyNetwork(ModelConfig()))
        with self.assertRaisesRegex(ValueError, "peer_context"):
            migrate_peer_context(PolicyNetwork(peer_model()))

    def test_migration_zeros_only_corresponding_adam_moments_and_keeps_step(self):
        old = PolicyNetwork(ModelConfig(hidden_size=16, entity_size=8, public_context=True))
        network = migrate_peer_context(old)
        optimizer = torch.optim.Adam(network.parameters(), lr=0.0003, amsgrad=True)
        for parameter in network.parameters():
            optimizer.state[parameter] = {
                "step": torch.tensor(8750.0), "exp_avg": torch.ones_like(parameter),
                "exp_avg_sq": torch.full_like(parameter, 2),
                "max_exp_avg_sq": torch.full_like(parameter, 3),
            }
        before = copy.deepcopy(optimizer.state_dict())
        reset_peer_context_optimizer(network, optimizer)
        agent_weight = network.entity_encoders[ENTITY_TYPES.index("Agent")][0].weight
        for group, saved_group in zip(optimizer.param_groups, before["param_groups"], strict=True):
            for parameter, index in zip(group["params"], saved_group["params"], strict=True):
                for name, actual in optimizer.state[parameter].items():
                    expected = before["state"][index][name].clone()
                    if parameter is agent_weight and name != "step":
                        expected[:, 8:10] = 0
                    self.assertTrue(torch.equal(actual, expected), name)
        self.assertEqual(optimizer.state_dict()["param_groups"], before["param_groups"])
        with self.assertRaisesRegex(ValueError, "bound"):
            reset_peer_context_optimizer(network, torch.optim.Adam(old.parameters()))

    def test_cache_packing_and_chunk_recurrence_use_the_peer_schema(self):
        frames, history = [], {}
        for tick in range(3):
            step = peer_step()
            step.sim_time = tick + 1
            if tick == 1:
                step.agent_status.pop(1)
                step.n_agents -= 1
            if tick == 2:
                step.agent_status.reverse()
            actions = tuple(ConstantTeacher().act(step))
            frames.append((step, actions, history))
            history = {action.agent_id: action for action in actions}
        for encoder in ("pool", "attention"):
            for memory in ("none", "gru"):
                config = peer_model(encoder=encoder, memory=memory)
                cached = cache_frames(frames, config)
                packed = pack_sequence(cached, config)
                self.assert_batch_equal(packed.features, pack_sequence(frames, config).features)
                network = PolicyNetwork(config)
                hidden, identities, outputs = None, (), []
                with torch.no_grad():
                    for step, _, history in frames:
                        features = encode_step(step, history, public_context=True, peer_context=True)
                        hidden = align_hidden(identities, features.agent_ids, hidden, hidden_size=16, device="cpu")
                        output = network(features, hidden)
                        hidden, identities = output.next_hidden, features.agent_ids
                        outputs.append(output.mean)
                    torch.testing.assert_close(forward_sequence(network, packed).mean, torch.cat(outputs),
                                               atol=1e-6, rtol=1e-5)
                with self.assertRaisesRegex(ValueError, "schema"):
                    pack_sequence(cached, config.model_copy(update={"peer_context": False}))

    def test_collector_encodes_peer_features_for_action_and_bootstrap_only_with_synthetic_dtos(self):
        class PeerEnvironment(ScriptedEnvironment):
            def reset(self, seed):
                super().reset(seed)
                self.observation = peer_step()
                return self.observation

            def step(self, actions):
                transition = super().step(actions)
                self.observation = peer_step()
                self.observation.sim_time = self.position + 1
                return replace(transition, observation=self.observation)

        config = make_config("imitation", model=peer_model().model_dump())
        network = PolicyNetwork(config.model)
        observed = []
        handle = network.register_forward_pre_hook(lambda _, inputs: observed.append(inputs[0]))
        self.addCleanup(handle.remove)
        environment = PeerEnvironment(identities=((2, 9, 31),) * 2, rewards=(1,), terminal_at_end=False)
        with RolloutCollector(config, network, emit=lambda _: None, environment_factory=lambda: environment,
                              teacher_factory=ConstantTeacher) as collector:
            result = collector.collect(1, policy_version=0, teacher_probability=1)
        self.assertEqual(len(observed), 2)
        for features in observed:
            self.assertEqual(features.feature_version, PEER_FEATURE_VERSION)
            np.testing.assert_allclose(features.entities[3, 8:], [0.6, math.log1p(9)], rtol=1e-6)
        self.assertEqual(result.trajectories[0][0].features.feature_version, PEER_FEATURE_VERSION)

    def test_checkpoint_roundtrip_and_tagless_legacy_model_configs(self):
        for public, peer in ((False, False), (True, False), (True, True)):
            config = pipeline_config("imitation").model_copy(update={
                "model": ModelConfig(hidden_size=16, entity_size=8, public_context=public,
                                     peer_context=peer, angle_head="vector_bc"),
            })
            network = PolicyNetwork(config.model)
            with self.subTest(public=public, peer=peer), tempfile.TemporaryDirectory() as directory:
                path = Path(directory) / "checkpoint.pt"
                save_checkpoint(path, network, config)
                payload = torch.load(path, weights_only=True)
                teacher = copy.deepcopy(payload["teacher"])
                if not peer:
                    payload["config"]["model"].pop("peer_context")
                    torch.save(payload, path)
                    sidecar = read_json(path.with_suffix(".pt.json"))
                    sidecar["model"].pop("peer_context")
                    sidecar["sha256"] = file_hash(path)
                    write_json(path.with_suffix(".pt.json"), sidecar)
                loaded = load_checkpoint(path, expected_model=config.model)
                self.assertEqual(loaded.config.teacher, config.teacher)
                self.assertEqual(loaded.config.model.peer_context, peer)
                self.assertEqual(NeuralPolicy(network, 4).act(peer_step()), NeuralPolicy(loaded.network, 4).act(peer_step()))
                saved = Path(directory) / "resaved.pt"
                save_checkpoint(saved, loaded.network, loaded.config)
                restored = torch.load(saved, weights_only=True)
                self.assertEqual(restored["teacher"], teacher)
                self.assertEqual(restored["feature_version"], feature_version(public, peer))
                self.assertEqual(read_json(saved.with_suffix(".pt.json"))["feature_version"], feature_version(public, peer))
                if peer:
                    restored["feature_version"] = PUBLIC_FEATURE_VERSION
                    torch.save(restored, saved)
                    sidecar = read_json(saved.with_suffix(".pt.json"))
                    sidecar["sha256"] = file_hash(saved)
                    write_json(saved.with_suffix(".pt.json"), sidecar)
                    with self.assertRaisesRegex(ValueError, "feature schema"):
                        load_checkpoint(saved)

    def test_replay_tensor_and_json_roundtrips_preserve_same_width_schema_and_legacy(self):
        template = make_frame(TinyPolicy(ModelConfig(hidden_size=16, entity_size=8)), peer_step())
        for public, peer in ((False, False), (True, False), (True, True)):
            dataset = ImitationDataset(2)
            features = encode_step(template.step, public_context=public, peer_context=peer)
            dataset.extend(Rollout(((replace(template, features=features),),), (0,), 0, {}))
            stream = io.BytesIO()
            torch.save(dataset.state_dict(), stream)
            stream.seek(0)
            restored = ImitationDataset(2)
            restored.load_state_dict(torch.load(stream, weights_only=True))
            self.assert_batch_equal(features, restored.frames[0].features)
            snapshot = json.loads(json.dumps(dataset.json_snapshot(), allow_nan=False))
            restored.load_json_snapshot(snapshot)
            self.assertEqual(restored.json_snapshot(), snapshot)
            if not peer:
                state = dataset.state_dict()
                state.pop("feature_version")
                state["frames"][0]["features"].pop("feature_version")
                restored.load_state_dict(state)
                self.assert_batch_equal(features, restored.frames[0].features)
                snapshot["frames"][0]["features"].pop("feature_version")
                restored.load_json_snapshot(snapshot)
                self.assert_batch_equal(features, restored.frames[0].features)
            else:
                snapshot["frames"][0]["features"]["feature_version"] = PUBLIC_FEATURE_VERSION
                with self.assertRaisesRegex(ValueError, "schema"):
                    restored.load_json_snapshot(snapshot)
                dataset.extend(Rollout(((replace(template, features=encode_step(
                    template.step, public_context=True,
                )),),), (0,), 0, {}))
                with self.assertRaisesRegex(ValueError, "mix feature"):
                    dataset.json_snapshot()


if __name__ == "__main__":
    unittest.main()
